### ISSUE TITLE
Share model file 

### ISSUE THREAD

**Issue by kyhoolee** [wiktorlazarski/head-segmentation#22]
Hi can you upload your model file on google drive or somewhere else to share it 
I can't not get it directly from your repo
https://github.com/wiktorlazarski/head-segmentation/blob/master/head_segmentation/model/resnet34_512.ckpt

**Comment by wiktorlazarski** [comment]
You have to use the Git LFS command `git lfs pull` to download the model. If this doesn't work for you feel free to download the model from https://drive.google.com/file/d/1Asm8JMFQwiHGGuQLXG_qnHvspWGdGuxw/view?usp=sharing.
