### ISSUE TITLE
Share mobilenet based model

### ISSUE THREAD

**Issue by kyhoolee** [wiktorlazarski/head-segmentation#24]
Hi, thank you for sharing resnet34 based model
Can you please also share mobilenetv2 based model?
And if yes please share it on google drive, I am not so familar with git lfs

**Comment by wiktorlazarski** [comment]
Hi, sure:
https://drive.google.com/file/d/1WXzf68rUFcdWGbY-Rm_nwpigEWmv1FtC/view?usp=sharing
https://drive.google.com/file/d/1nGkBs8GkX9tAhKq5gn7RXG5LS9rwikjx/view?usp=sharing

**Comment by okaris** [comment]
Hi @wiktorlazarski the links unfortunately do not work anymore.
