### ISSUE TITLE
Model outputs different result in Google Colab & when Run on a CPU based computer

### ISSUE THREAD

**Issue by pillai-karthik** [wiktorlazarski/head-segmentation#26]
When I run the model on Google Colab, the head segmentation is perfect, but when the same model is run using the pip library on the local computer (CPU) the segmentation is not at all good. Also, it outputs different results on different computers.

**Comment by wiktorlazarski** [comment]
Hi @pillai-karthik, 

Thank you for raising this issue 🚀 . We weren't aware of it. Could you provide some more details? For example which OS you are using + some exemplary outputs of a model from the Google Colab and your machine would be nice. Additionally, I have to request some source code snippets showing how you load an image and use a model.

Best regards,
Wiktor 🤗

**Comment by pillai-karthik** [comment]
Hi @wiktorlazarski,

Thank you for the quick response! 🚀 

Currently using the model like this - 

```
import head_segmentation.segmentation_pipeline as seg_pipeline
segmentation_pipeline = seg_pipeline.HumanHeadSegmentationPipeline()

def segment_head(image):
  segmentation_map = segmentation_pipeline(image)
  return image * cv2.cvtColor(segmentation_map, cv2.COLOR_GRAY2RGB)

image = cv2.imread(INPUT_DIR + image_name)
#image in NumPy array
image = segment_head(image)
cv2.imwrite("out.jpg",image)
```
OS: Windows 10 Pro

Image Examples -

Example 1:

Input-
![image (21)](https://user-images.githubusercontent.com/52003038/192251385-f2c33c20-8d5c-4098-87c9-f456d8aed0eb.jpg)
Google Colab -
![download](https://user-images.githubusercontent.com/52003038/192251508-b97f2ae7-7002-447e-a44c-d4e107354fe7.png)
Local -
![image (21)](https://user-images.githubusercontent.com/52003038/192251969-a03a06b7-9995-41e9-abeb-55297785d4b8.png)

Example 2:

Input-
![download](https://user-images.githubusercontent.com/52003038/192251784-2baaf051-df5f-48f4-a95c-ba27bb00e6cb.jpg)
Google Colab -
![download](https://user-images.githubusercontent.com/52003038/192251806-29387f9a-4f3c-4942-94f0-2dad867594f9.png)
Local -
![image (16)](https://user-images.githubusercontent.com/52003038/192251850-26ad8107-07a7-46ac-996c-3da7e973b84d.png)

Example 3:

Input-
![download](https://user-images.githubusercontent.com/52003038/192252328-81bd6a23-30ab-4203-bb3c-29937cad41e8.jpg)
Google Colab -
![download](https://user-images.githubusercontent.com/52003038/192252359-c80558e6-044a-4423-84b2-510fd66e95b8.png)
Local -
![image (6)](https://user-images.githubusercontent.com/52003038/192252387-8264a47b-5f59-4d8a-9b9f-e854f8f2b788.png)

**Comment by pillai-karthik** [comment]
@wiktorlazarski Solution to the issue -

OpenCV by default loads color images to BGR format. The model was trained with RGB images.

To covert use - 
`image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)`
