### ISSUE TITLE
pytorch_lightning 2.1.0 related error

### ISSUE THREAD

**Issue by karaposu** [wiktorlazarski/head-segmentation#34]
Versions are deleted from requirements.txt and this causes default install to install version 2.1.0. And if i run train.py using this version i get following error :  

<img width="676" alt="Screenshot 2023-10-20 at 22 55 45" src="https://github.com/wiktorlazarski/head-segmentation/assets/31979644/eebd83ed-07fd-4528-a65a-7412f9ab0ab2">

However if i downgrade pytorch_lightning to version 1.9.0 this error disappers. 

I am using M1 Mac and OS version is 13.3.

**Comment by wiktorlazarski** [comment]
Hey, thanks for bringing our attention to it. I have a small request. This issue doesn't seem complicated. Can you make a PR with pinned versions of all the packages we use in the project that are specified in the `requirements.txt` file?

Thanks in advance,
Wiktor

**Comment by karaposu** [comment]
sure Wiktor. I noticed a couple of more issues. Once i figure them all i will make a PR request

**Comment by wiktorlazarski** [comment]
Brilliant! Thanks a lot. Let us know if you have some questions or you'd like to discuss some best options for the project.
